# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "NETWORG | Blog"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Read our experiences while we help others
twitter_username: thenetworg
github_username: networg
minimal_mistakes_skin: default
search: true

twitter:
  username: "thenetworg"
social:
  type: Organization
  name: NETWORG
  links:
    - "https://networg.com"
    - "https://twitter.com/thenetworg"
    - "https://www.facebook.com/thenetworg"
    - "https://instagram.com/thenetworg"
    - "https://github.com/networg"
    - "https://www.linkedin.com/company/networg/"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:year/:month/:day/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  avatar : "/assets/images/networg.png"
  bio    : "Read our experiences while we help others"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://networg.com"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://fb.me/thenetworg"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thenetworg"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/networg"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/thenetworg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/networg/"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://fb.me/thenetworg"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thenetworg"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/networg"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/thenetworg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/networg/"

collections:
  authors:
    output: true

defaults:
  # _authors
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

feed:
  path: /feed/index.xml

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-73142323-4"
    anonymize_ip: false # default

repository: networg/networg.github.io # Git username/repo-name e.g. "mmistakes/minimal-mistakes"
comments:
  provider: "staticman_v2"
  staticman:
    branch: "master"
    endpoint: https://hajekj-staticman.azurewebsites.net/v3/entry/github/

reCaptcha:
  siteKey: "6LfU-9UUAAAAAKoZxSz_xhPHYtXlMtpiPSHxN9uy"
  # Encrypt reCaptcha secret key using Staticman /encrypt endpoint
  # For more information, https://staticman.net/docs/encryption
  secret: "d9rizJFrrCJ2iNHhM0+y71EkuIuLI7eaRaehzFrBdzemBhXuCprSa03v1Lj41LCsE9NMUrs/TWQEqjoGj1zN+XAFj65axEdOaGPx64XryzlJTK1hI/S3HUe2WyDsmGoXJtgUxqpwRVj52H0k9PjmdqLXoNm+1tEffZIYpunnLm0vAXcUjKxPclAf6olZSsNyJuZtPnHiuS9pbadgz8SDFqtBD1lwHXGk9UBy+Wbl6YdeJAKek4jRaTa/HlNB2tGl30uM+jGgdUMJjAc3L7Qhv8mTGb8zQBY28M8Fs38Bumf4LpRUhFw+ZG9nr5SrbUzaFDZ6+3lAkkikqNEM3h+RJQ=="